<a href="https://colab.research.google.com/github/Suphattha/data_viz/blob/main/More_advanced_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##list หน้าตาประมาณนี้
list ดีกว่า array เพราะ list สามารถเก็บได้หลายอย่าง ทำได้ทั้ง str และ number

##Dictionary
สามารถ index ด้วยอะไรก็ได้ แต่ลำดับจะหายไป

In [68]:
ex_dict = {'a':10,'1':1, 'stat':5} #curly brackets ในการบอกว่าเป็น dict

In [69]:
ex_dict['stat']

5

In [70]:
ex2_dict = {1:'one', 2:'two', 3:'three'}

In [71]:
ex2_dict[2]

'two'

##การเพิ่มสมาชิก

In [72]:
ex2_dict[0] = 'zero'

In [73]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}


คำสั่ง
.keys() ดูว่ามีindexอะไรบ้าง
.values() ดูค่าของมัน

In [74]:
ex2_dict.keys()

dict_keys([1, 2, 3, 0])

In [75]:
for index in ex2_dict.keys() :
    print(index)

1
2
3
0


In [76]:
ex2_dict.values()

dict_values(['one', 'two', 'three', 'zero'])

In [77]:
index

0

dict เอาไปใช้ร่วมกับ dataframe ของ pandas
Numpy array (array n มิติ)
numpy คือ packege ที่ทำงานเกี่ยวกับ array ของตัวเลข(ที่มีคนเขียนขึ้นมาและนิยมใช้ )
numpy -> number python

In [78]:
import numpy #วิธีเรียกใช้งาน package

In [79]:
import numpy as np

สร้าง numpy array

In [80]:
ex_2d_array = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]



การชี้ค่าใน array

In [81]:
ex_2d_array[1,2]

0.3

In [82]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]] #การชี้ list
len(list_x)

2

In [83]:
list_x[1][2]

0.3

operations

In [84]:
ex2_2d_array = np.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [85]:
ex_2d_array.shape #.shape ตรวจขนาดของ matrix

(2, 3)

In [86]:
ex2_2d_array + ex_2d_array

array([[6.2, 3. , 4.5],
       [9.1, 0.1, 1.3]])

In [87]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
list_x2 = [[1,0,0],[0,0,1]]
list_x + list_x2

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3], [1, 0, 0], [0, 0, 1]]

In [88]:
ex2_2d_array - ex_2d_array

array([[-4.2, -3. , -4.5],
       [-9.1, -0.1,  0.7]])

In [89]:
ex2_2d_array * ex_2d_array #การคูณแบบ array เอาตำแหน่งเดียวกันมาคูณกัน

array([[5.2, 0. , 0. ],
       [0. , 0. , 0.3]])

matrix multiplication (dot product)

In [90]:
print(ex_2d_array)
print(ex_2d_array.T)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[5.2 9.1]
 [3.  0.1]
 [4.5 0.3]]


In [91]:
dot_mat = np.dot(ex2_2d_array,ex_2d_array.T)
print(dot_mat)

[[5.2 9.1]
 [4.5 0.3]]


In [92]:
np.linalg.det(dot_mat)

-39.389999999999986

search google -> stackoverflow หรือ web ของ package สำหรับ operation อื่นๆ

##Matrix Slicing

In [93]:
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [94]:
ex_2d_array[1,1:]

array([0.1, 0.3])

In [95]:
ex_2d_array[:,:2]

array([[5.2, 3. ],
       [9.1, 0.1]])

HW5 เขียน Function คูณ matrix
แล้ว test กับ matrix

(2,3)*(3,2)

(4,4)*(4,1)

(2,2)*(2,2)


In [96]:
import numpy as np

In [97]:
#Matrix 2*3
mat_A = np.array([[1,7,5],[9,2,4]])
mat_A

array([[1, 7, 5],
       [9, 2, 4]])

In [98]:
#Matrix 3*2
mat_B = np.array([[4,6],[5,3],[8,7]])
mat_B

array([[4, 6],
       [5, 3],
       [8, 7]])

In [99]:
#Matrix 4*4
mat_C = np.array([[7,4,1,9],[8,9,4,6],[7,1,5,4],[5,4,3,2]])
mat_C

array([[7, 4, 1, 9],
       [8, 9, 4, 6],
       [7, 1, 5, 4],
       [5, 4, 3, 2]])

In [100]:
#Matrix 4*1
mat_D = np.array([[9],[6],[7],[4]])
mat_D

array([[9],
       [6],
       [7],
       [4]])

In [101]:
#Matrix 2*2 
mat_E = np.array([[9,8],[7,6]])
mat_E

array([[9, 8],
       [7, 6]])

In [102]:
mat_F = np.array([[6,4],[5,7]])
mat_F

array([[6, 4],
       [5, 7]])

##Create Function Multiply Matrix

In [103]:
def mul_mat(A, B):
    C = [[0 for row in range(len(B[0]))] for col in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                C[i][j] += A[i][k]*B[k][j]
    r = np.matrix(C)
    return r

In [104]:
mul_mat(mat_A,mat_B)

matrix([[79, 62],
        [78, 88]])

In [105]:
mul_mat(mat_C,mat_D)

matrix([[130],
        [178],
        [120],
        [ 98]])

In [106]:
mul_mat(mat_E,mat_F)

matrix([[94, 92],
        [72, 70]])

##ตรวจสอบความถูกต้อง

In [107]:
np.dot(mat_A,mat_B)

array([[79, 62],
       [78, 88]])