<a href="https://colab.research.google.com/github/Suphattha/data_viz/blob/main/More_advanced_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##list หน้าตาประมาณนี้
list ดีกว่า array เพราะ list สามารถเก็บได้หลายอย่าง ทำได้ทั้ง str และ number

##Dictionary
สามารถ index ด้วยอะไรก็ได้ แต่ลำดับจะหายไป

In [ ]:
ex_dict = {'a':10,'1':1, 'stat':5} #curly brackets ในการบอกว่าเป็น dict

In [ ]:
ex_dict['stat']

5

In [ ]:
ex2_dict = {1:'one', 2:'two', 3:'three'}

In [ ]:
ex2_dict[2]

'two'

##การเพิ่มสมาชิก

In [ ]:
ex2_dict[0] = 'zero'

In [ ]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}


คำสั่ง
.keys() ดูว่ามีindexอะไรบ้าง
.values() ดูค่าของมัน

In [ ]:
ex2_dict.keys()

dict_keys([1, 2, 3, 0])

In [ ]:
for index in ex2_dict.keys() :
    print(index)

1
2
3
0


In [ ]:
ex2_dict.values()

dict_values(['one', 'two', 'three', 'zero'])

In [ ]:
index

0

dict เอาไปใช้ร่วมกับ dataframe ของ pandas
Numpy array (array n มิติ)
numpy คือ packege ที่ทำงานเกี่ยวกับ array ของตัวเลข(ที่มีคนเขียนขึ้นมาและนิยมใช้ )
numpy -> number python

In [ ]:
import numpy #วิธีเรียกใช้งาน package

In [ ]:
import numpy as np

สร้าง numpy array

In [ ]:
ex_2d_array = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]



การชี้ค่าใน array

In [ ]:
ex_2d_array[1,2]

0.3

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]] #การชี้ list
len(list_x)

2

In [ ]:
list_x[1][2]

0.3

operations

In [ ]:
ex2_2d_array = np.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]


NameError: ignored

In [ ]:
ex_2d_array.shape #.shape ตรวจขนาดของ matrix

NameError: ignored

In [ ]:
ex2_2d_array + ex_2d_array

NameError: ignored

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
list_x2 = [[1,0,0],[0,0,1]]
list_x + list_x2

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3], [1, 0, 0], [0, 0, 1]]

In [ ]:
ex2_2d_array - ex_2d_array

NameError: ignored

In [ ]:
ex2_2d_array * ex_2d_array #การคูณแบบ array เอาตำแหน่งเดียวกันมาคูณกัน

NameError: ignored

matrix multiplication (dot product)

In [ ]:
print(ex_2d_array)
print(ex_2d_array.T)

NameError: ignored

In [ ]:
dot_mat = np.dot(ex2_2d_array,ex_2d_array.T)
print(dot_mat)

NameError: ignored

In [ ]:
np.linalg.det(dot_mat)

NameError: ignored

search google -> stackoverflow หรือ web ของ package สำหรับ operation อื่นๆ

##Matrix Slicing

In [ ]:
print(ex_2d_array)

NameError: ignored

In [ ]:
ex_2d_array[1,1:]

NameError: ignored

In [ ]:
ex_2d_array[:,:2]

NameError: ignored

HW5 เขียน Function คูณ matrix
แล้ว test กับ matrix

(2,3)*(3,2)

(4,4)*(4,1)

(2,2)*(2,2)
