<a href="https://colab.research.google.com/github/Suphattha/data_viz/blob/main/More_advanced_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##list หน้าตาประมาณนี้
list ดีกว่า array เพราะ list สามารถเก็บได้หลายอย่าง ทำได้ทั้ง str และ number

##Dictionary
สามารถ index ด้วยอะไรก็ได้ แต่ลำดับจะหายไป

In [1]:
ex_dict = {'a':10,'1':1, 'stat':5} #curly brackets ในการบอกว่าเป็น dict

In [2]:
ex_dict['stat']

5

In [3]:
ex2_dict = {1:'one', 2:'two', 3:'three'}

In [4]:
ex2_dict[2]

'two'

##การเพิ่มสมาชิก

In [5]:
ex2_dict[0] = 'zero'

In [6]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}


คำสั่ง
.keys() ดูว่ามีindexอะไรบ้าง
.values() ดูค่าของมัน

In [7]:
ex2_dict.keys()

dict_keys([1, 2, 3, 0])

In [8]:
for index in ex2_dict.keys() :
    print(index)

1
2
3
0


In [9]:
ex2_dict.values()

dict_values(['one', 'two', 'three', 'zero'])

In [10]:
index

0

dict เอาไปใช้ร่วมกับ dataframe ของ pandas
Numpy array (array n มิติ)
numpy คือ packege ที่ทำงานเกี่ยวกับ array ของตัวเลข(ที่มีคนเขียนขึ้นมาและนิยมใช้ )
numpy -> number python

In [11]:
import numpy #วิธีเรียกใช้งาน package

In [12]:
import numpy as np

สร้าง numpy array

In [13]:
ex_2d_array = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]



การชี้ค่าใน array

In [14]:
ex_2d_array[1,2]

0.3

In [15]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]] #การชี้ list
len(list_x)

2

In [16]:
list_x[1][2]

0.3

operations

In [17]:
ex2_2d_array = np.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [18]:
ex_2d_array.shape #.shape ตรวจขนาดของ matrix

(2, 3)

In [19]:
ex2_2d_array + ex_2d_array

array([[6.2, 3. , 4.5],
       [9.1, 0.1, 1.3]])

In [20]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
list_x2 = [[1,0,0],[0,0,1]]
list_x + list_x2

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3], [1, 0, 0], [0, 0, 1]]

In [21]:
ex2_2d_array - ex_2d_array

array([[-4.2, -3. , -4.5],
       [-9.1, -0.1,  0.7]])

In [22]:
ex2_2d_array * ex_2d_array #การคูณแบบ array เอาตำแหน่งเดียวกันมาคูณกัน

array([[5.2, 0. , 0. ],
       [0. , 0. , 0.3]])

matrix multiplication (dot product)

In [23]:
print(ex_2d_array)
print(ex_2d_array.T)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[5.2 9.1]
 [3.  0.1]
 [4.5 0.3]]


In [24]:
dot_mat = np.dot(ex2_2d_array,ex_2d_array.T)
print(dot_mat)

[[5.2 9.1]
 [4.5 0.3]]


In [25]:
np.linalg.det(dot_mat)

-39.389999999999986

search google -> stackoverflow หรือ web ของ package สำหรับ operation อื่นๆ

##Matrix Slicing

In [41]:
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [42]:
ex_2d_array[1,1:]

array([0.1, 0.3])

In [43]:
ex_2d_array[:,:2]

array([[5.2, 3. ],
       [9.1, 0.1]])

HW5 เขียน Function คูณ matrix
แล้ว test กับ matrix

(2,3)*(3,2)

(4,4)*(4,1)

(2,2)*(2,2)


In [44]:
import numpy as np

In [45]:
#Matrix 2*3
mat_A = np.array([[1,4,2],[2,8,7]])
mat_A

array([[1, 4, 2],
       [2, 8, 7]])

In [46]:
#Matrix 3*2
mat_B = np.array([[4,2],[6,8],[2,1]])
mat_B

array([[4, 2],
       [6, 8],
       [2, 1]])

In [47]:
#Matrix 4*4
mat_C = np.array([[1,5,4,3],[5,2,1,4],[9,6,2,4],[1,3,2,4]])
mat_C

array([[1, 5, 4, 3],
       [5, 2, 1, 4],
       [9, 6, 2, 4],
       [1, 3, 2, 4]])

In [48]:
#Matrix 4*1
mat_D = np.array([[1],[4],[5],[7]])
mat_D

array([[1],
       [4],
       [5],
       [7]])

In [49]:
#Matrix 2*2 
mat_E = np.array([[5,1],[4,2]])
mat_E

array([[5, 1],
       [4, 2]])

In [50]:
mat_F = np.array([[1,8],[7,3]])
mat_F

array([[1, 8],
       [7, 3]])

##Create Function Multiply Matrix

In [36]:
def mul_mat(A, B):
    C = [[0 for row in range(len(B[0]))] for col in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                C[i][j] += A[i][k]*B[k][j]
    r = np.matrix(C)
    return r

In [37]:
mul_mat(mat_A,mat_B)

matrix([[32, 36],
        [70, 75]])

In [38]:
mul_mat(mat_C,mat_D)

matrix([[62],
        [46],
        [71],
        [51]])

In [39]:
mul_mat(mat_E,mat_F)

matrix([[12, 43],
        [18, 38]])

##ตรวจสอบความถูกต้อง

In [40]:
np.dot(mat_A,mat_B)

array([[32, 36],
       [70, 75]])