<a href="https://colab.research.google.com/github/Suphattha/data_viz/blob/main/More_advanced_data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##list หน้าตาประมาณนี้
list ดีกว่า array เพราะ list สามารถเก็บได้หลายอย่าง ทำได้ทั้ง str และ number

##Dictionary
สามารถ index ด้วยอะไรก็ได้ แต่ลำดับจะหายไป

In [ ]:
ex_dict = {'a':10,'1':1, 'stat':5} #curly brackets ในการบอกว่าเป็น dict

In [ ]:
ex_dict['stat']

5

In [ ]:
ex2_dict = {1:'one', 2:'two', 3:'three'}

In [ ]:
ex2_dict[2]

'two'

##การเพิ่มสมาชิก

In [ ]:
ex2_dict[0] = 'zero'

In [ ]:
ex2_dict

{0: 'zero', 1: 'one', 2: 'two', 3: 'three'}


คำสั่ง
.keys() ดูว่ามีindexอะไรบ้าง
.values() ดูค่าของมัน

In [ ]:
ex2_dict.keys()

dict_keys([1, 2, 3, 0])

In [ ]:
for index in ex2_dict.keys() :
    print(index)

1
2
3
0


In [ ]:
ex2_dict.values()

dict_values(['one', 'two', 'three', 'zero'])

In [ ]:
index

0

dict เอาไปใช้ร่วมกับ dataframe ของ pandas
Numpy array (array n มิติ)
numpy คือ packege ที่ทำงานเกี่ยวกับ array ของตัวเลข(ที่มีคนเขียนขึ้นมาและนิยมใช้ )
numpy -> number python

In [ ]:
import numpy #วิธีเรียกใช้งาน package

In [ ]:
import numpy as np

สร้าง numpy array

In [ ]:
ex_2d_array = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]



การชี้ค่าใน array

In [ ]:
ex_2d_array[1,2]

0.3

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]] #การชี้ list
len(list_x)

2

In [ ]:
list_x[1][2]

0.3

operations

In [ ]:
ex2_2d_array = np.array([[1,0,0],[0,0,1]])
print(ex2_2d_array)
print(ex_2d_array)

[[1 0 0]
 [0 0 1]]
[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array.shape #.shape ตรวจขนาดของ matrix

(2, 3)

In [ ]:
ex2_2d_array + ex_2d_array

array([[6.2, 3. , 4.5],
       [9.1, 0.1, 1.3]])

In [ ]:
list_x = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
list_x2 = [[1,0,0],[0,0,1]]
list_x + list_x2

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3], [1, 0, 0], [0, 0, 1]]

In [ ]:
ex2_2d_array - ex_2d_array

array([[-4.2, -3. , -4.5],
       [-9.1, -0.1,  0.7]])

In [ ]:
ex2_2d_array * ex_2d_array #การคูณแบบ array เอาตำแหน่งเดียวกันมาคูณกัน

array([[5.2, 0. , 0. ],
       [0. , 0. , 0.3]])

matrix multiplication (dot product)

In [ ]:
print(ex_2d_array)
print(ex_2d_array.T)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[5.2 9.1]
 [3.  0.1]
 [4.5 0.3]]


In [ ]:
dot_mat = np.dot(ex2_2d_array,ex_2d_array.T)
print(dot_mat)

[[5.2 9.1]
 [4.5 0.3]]


In [ ]:
np.linalg.det(dot_mat)

-39.389999999999986

search google -> stackoverflow หรือ web ของ package สำหรับ operation อื่นๆ

##Matrix Slicing

In [ ]:
print(ex_2d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [ ]:
ex_2d_array[1,1:]

array([0.1, 0.3])

In [ ]:
ex_2d_array[:,:2]

array([[5.2, 3. ],
       [9.1, 0.1]])

HW5 เขียน Function คูณ matrix
แล้ว test กับ matrix

(2,3)*(3,2)

(4,4)*(4,1)

(2,2)*(2,2)


In [ ]:
import numpy as np

In [ ]:
#Matrix 2*3
mat_A = np.array([[1,7,5],[9,2,4]])
mat_A

array([[1, 7, 5],
       [9, 2, 4]])

In [ ]:
#Matrix 3*2
mat_B = np.array([[4,6],[5,3],[8,7]])
mat_B

array([[4, 6],
       [5, 3],
       [8, 7]])

In [ ]:
#Matrix 4*4
mat_C = np.array([[7,4,1,9],[8,9,4,6],[7,1,5,4],[5,4,3,2]])
mat_C

array([[7, 4, 1, 9],
       [8, 9, 4, 6],
       [7, 1, 5, 4],
       [5, 4, 3, 2]])

In [ ]:
#Matrix 4*1
mat_D = np.array([[9],[6],[7],[4]])
mat_D

array([[9],
       [6],
       [7],
       [4]])

In [ ]:
#Matrix 2*2 
mat_E = np.array([[9,8],[7,6]])
mat_E

array([[9, 8],
       [7, 6]])

In [ ]:
mat_F = np.array([[6,4],[5,7]])
mat_F

array([[6, 4],
       [5, 7]])

##Create Function Multiply Matrix

In [ ]:
def mul_mat(A, B):
    C = [[0 for row in range(len(B[0]))] for col in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                C[i][j] += A[i][k]*B[k][j]
    r = np.matrix(C)
    return r

In [ ]:
mul_mat(mat_A,mat_B)

matrix([[79, 62],
        [78, 88]])

In [ ]:
mul_mat(mat_C,mat_D)

matrix([[130],
        [178],
        [120],
        [ 98]])

In [ ]:
mul_mat(mat_E,mat_F)

matrix([[94, 92],
        [72, 70]])

##ตรวจสอบความถูกต้อง

In [ ]:
np.dot(mat_A,mat_B)

array([[79, 62],
       [78, 88]])

##zeros, ones, random

In [1]:
import numpy as np

In [2]:
np.zeros(2)

array([0., 0.])

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

##Ones

In [5]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

##Matrix Operation (scalar multiplication)

In [6]:
M_ones = np.ones((2,3))

In [7]:
2*M_ones

array([[2., 2., 2.],
       [2., 2., 2.]])

##Random

In [8]:
np.random.rand(3,2) #Uniform random(0,1)

array([[0.70533635, 0.31701611],
       [0.18244268, 0.2434961 ],
       [0.73417025, 0.33093997]])

In [9]:
np.random.randn(3,2) #normal mean = 0 std = 1

array([[ 0.91136999, -0.46751885],
       [-0.49923316, -1.26468441],
       [-0.72660415, -0.2360907 ]])

In [10]:
np.random.choice([1,2,3,'a','b','c'])

'3'

In [11]:
np.random.choice([1,2,3,28,11,100],size = (2,3), replace=False)

array([[100,   2,  11],
       [ 28,   3,   1]])

In [12]:
np.random.choice(['A','B','C','D','F'], size=35,p=[0.1,0.2,0.4,0.29,0.01])

array(['A', 'D', 'B', 'D', 'C', 'C', 'C', 'B', 'C', 'B', 'C', 'C', 'D',
       'D', 'C', 'D', 'B', 'C', 'C', 'D', 'D', 'C', 'C', 'C', 'C', 'C',
       'D', 'D', 'C', 'C', 'D', 'C', 'C', 'D', 'D'], dtype='<U1')

##เฉลย HW Multiply Matrix

In [13]:

def mat_mul(A,B):
    C = np.zeros((A.shape[0],B.shape[1]))#เตรียมขนาดของ matrix ผลลัพธ์
    for r_a in range(A.shape[0]):
        for c_b in range(B.shape[1]):
            for every_element in range(A.shape[1]): 
                C[r_a,c_b] = C[r_a,c_b] + (A[r_a,every_element] * B[every_element,c_b])
    return C

In [15]:
mat1 = np.array([[1,2,3],[4,5,6]])
mat2 = np.array([[7,8],[9,10],[11,12]])

In [16]:
mat_mul(mat1,mat2)

array([[ 58.,  64.],
       [139., 154.]])